name = "spec"
version = "0.1.0"
defaultTargets = ["Spec"]

[[lean_lib]]
name = "Spec"

[[require]]
name = "aeneas"
path = "./vendor/aeneas/backends/lean"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.24.0"
